"""add parts table

Revision ID: 29ed4abd70d2
Revises: 0cb0e13ddd9a
Create Date: 2026-04-11 11:07:04.571129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ed4abd70d2'
down_revision: Union[str, Sequence[str], None] = '0cb0e13ddd9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('public_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    # ### end Alembic commands ###
