"""add category_code to categories

Revision ID: b53e2329096e
Revises: 93f4520c04c7
Create Date: 2026-04-11 12:10:35.431548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53e2329096e'
down_revision: Union[str, Sequence[str], None] = '93f4520c04c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_code', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'categories', ['category_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'category_code')
    # ### end Alembic commands ###
