"""add category_id to parts

Revision ID: c845b14265b7
Revises: 41b2581719b6
Create Date: 2026-04-11 11:26:18.472513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c845b14265b7'
down_revision: Union[str, Sequence[str], None] = '41b2581719b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('category_id', sa.UUID(), nullable=True))
    op.alter_column('parts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'parts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.alter_column('parts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('parts', 'category_id')
    # ### end Alembic commands ###
